id: P003314
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC361
  title: གེ་སར་སྒྲུང་གི་ས་མིང་ཞིབ་འཇུག་
  author: ''
  volumes:
    d20d8a305475448ebfe616637d90c8af:
      image_group_id: I4PD3943
      title: ''
      volume_number: 1
      total_pages: 616
