id: P003314
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 10:54:31.617899
source_metadata:
  id: bdr:W1AC361
  title: གེ་སར་སྒྲུང་གི་ས་མིང་ཞིབ་འཇུག་
  author: ''
  volumes:
    d20d8a305475448ebfe616637d90c8af:
      image_group_id: I4PD3943
      title: ''
      volume_number: 1
      total_pages: 616
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
