id: I504A43C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T04:58:57+00:00'
last_modified: '2022-06-07T20:22:39.292809+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC361
  title: གེ་སར་སྒྲུང་གི་ས་མིང་ཞིབ་འཇུག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2C39:
      image_group_id: I4PD3943
      title: ''
      total_pages: 616
      order: 1
      base_file: 2C39.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
